### PR TITLE
install cards blocks in dev env for testing

### PR DESCRIPTION
**Pull request by shawninder**
@comzeradd perhaps you can confirm that this is the right way to do this?

### CODE REVIEW

**Comment by shawninder** [comment]
I actually think this is not going to work. I think I need [this code](https://github.com/greenpeace/planet4-child-theme-canada/pull/4/files) somewhere but I'm not sure why that wasn't the right place for it.

**Comment by comzeradd** [comment]
You need a prefix for the package (eg. https://github.com/greenpeace/planet4-base/blob/main/production.json)

But that requires that `planet4-gpca-plugin-blocks` is added to packagist. See:
https://support.greenpeace.org/planet4/nro-customization/development/package-registry

**Comment by shawninder** [comment]
Oops, indeed, I just added the prefix in my last commit @comzeradd .

The package is published to packagist: https://packagist.org/packages/shawninder/planet4-gpca-plugin-blocks

What about the code that adds these new blocks to the whitelist? Where should that code reside if not in `planet4-child-theme-canada`? Does it make sense to include it in the `shawninder/planet4-gpca-plugin-blocks` package (or the `shawninder/cards` repo) itself? Is that even possible?

To be clear I'm talking about this PHP code:
```php
function p4_child_theme_gpca_whitelist_blocks( $allowed_blocks, $post ) {
	array_push($allowed_blocks, 'cards-block/card', 'cards-block/category', 'cards-block/list');
	return $allowed_blocks;
}

add_filter( 'allowed_block_types', 'p4_child_theme_gpca_whitelist_blocks', 10, 2 );
```

**Comment by comzeradd** [comment]
Ideally the plugin should live in the Greenpeace Github org. Ping me in Slack if you need more details on that.

The whitelist would make more sense to be in the plugin itself. See the [GPNL example](https://github.com/greenpeace/planet4-gpnl-plugin-gutenberg-blocks/blob/develop/planet4-gutenberg-blocks.php).

**Comment by shawninder** [comment]
Do you think we are ready to merge this @comzeradd ? Do you expect this to work?

**Pull request merged**
